version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: CathayUnited-db
    environment:
      MYSQL_ROOT_PASSWORD: a123456
      MYSQL_DATABASE: store
      MYSQL_USER: Ian
      MYSQL_PASSWORD: 861021
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - mysql-network
    restart: always

volumes:
  mysql-data:
    driver: local

networks:
  mysql-network:
    driver: bridge
